# Generated by Django 6.0.6 on 2026-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Credit / Debit Card (Mock)'), ('CASH', 'Cash on Delivery')], default='CARD', max_length=20, verbose_name='Payment Method'),
        ),
    ]
